CREATE TABLE [dbo].[STUDENT] (
    [S_ID]       INT            IDENTITY (1, 1) NOT NULL,
    [S_NAME]     NVARCHAR (20)  NOT NULL,
    [S_PASSWORD] NVARCHAR (20)  NOT NULL,
    [S_IMAGE]    NVARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([S_ID] ASC),
    UNIQUE NONCLUSTERED ([S_NAME] ASC)
);

