//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SETEXAM
    {
        public int EXAM_ID { get; set; }
        public Nullable<System.DateTime> EXAM_DATE { get; set; }
        public Nullable<int> EXAM_FK_STU { get; set; }
        public string EXAM_NAME { get; set; }
        public Nullable<int> STD_STD_SCORE { get; set; }
    
        public virtual STUDENT STUDENT { get; set; }
    }
}
