//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizz.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STUDENT()
        {
            this.SETEXAMs = new HashSet<SETEXAM>();
        }
    
        public int S_ID { get; set; }
        [Display(Name = "Student Name")]
        [Required(ErrorMessage = "*")]

        public string S_NAME { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "*")]

        public string S_PASSWORD { get; set; }
        public string S_IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SETEXAM> SETEXAMs { get; set; }
    }
}
